Social Media Exchanger/Models/SocialPage.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using System.Web.Mvc;

namespace Social_Media_Exchanger.Models
{
    public class SocialPage
    {
        public int Id { get; set; }

        public SocialPage()
        {
            Cpc = 10;
            Active = true;
            NumberOfClicks = 0;
            Deleted = false;
        }


        [MaxLength(50)]
        [Required]
        public string Name { get; set; }

        [Required]
        [MaxLength(350)]
        public virtual string Url { get; set; }

        [Range(2, 10)]
        public int Cpc { get; set; }

        [Range(0, Int32.MaxValue)]
        public int NumberOfClicks { get; set; }

        [Required]
        public bool Active { get; set; }

        public string UserId { get; set; }

        public virtual ApplicationUser User { get; set; }

        public bool Deleted { get; set; }
    }
}

Social Media Exchanger/ViewModels/EditViewModel.cs
using Social_Media_Exchanger.Models;
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace Social_Media_Exchanger.ViewModels
{
    public class EditViewModel
    {
        [Required]
        public int Id { get; set; }

        [Range(1, 3), Required]
        public int SocialNetworkId { get; set; }

        [Required, MaxLength(50)]
        public string Name { get; set; }

        [Required]
        public bool Active { get; set; }

        [Range(2, 10), Required]
        public int Cpc { get; set; }
    }
}

Social Media Exchanger/Controllers/SocialPageController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Social_Media_Exchanger.ViewModels;
using Microsoft.AspNet.Identity;
using Social_Media_Exchanger.Models;
using Social_Media_Exchanger.Utils;
using LinqToTwitter;
using System.Text.RegularExpressions;
using Google.Apis.YouTube.v3;
using Google.Apis.Services;

namespace Social_Media_Exchanger.Controllers
{
    [Authorize]
    public class SocialPageController : Controller
    {
        ApplicationDbContext _context;
        TwitterContext _twitterContext;


        public SocialPageController()
        {
            _context = new ApplicationDbContext();
            var auth = new SingleUserAuthorizer
            {
                CredentialStore = new SingleUserInMemoryCredentialStore
                {
                    ConsumerKey = "no3NWVxQRKC7Sw5bEFeN1PDtr",
                    ConsumerSecret = "NNoi1t2i05jiFlirXCWC54O91c7KJSeSke6ywSiJa08wU3DKO0",
                    AccessToken = "383165481-4IdMQqBohYjkvUUwwuLlHHrYWZxCeGkVayex1hlP",
                    AccessTokenSecret = "mFcpuXC92juYiEJ89QbC8Rmxi1F6X9ID5U78mk2QHiwDD"
                }
            };

            _twitterContext = new TwitterContext(auth);
        }


        [HttpPost]
        public ActionResult Add(SocialPageFormViewModel model)
        {
            bool error = false;
            var listaSocialNetworks = _context.SocialNetworks.ToList();
            if (!ModelState.IsValid)
            {
                model.SocialNetworks = listaSocialNetworks;
                return View("Add", model);
            }

            try
            {
                switch (model.SocialNetworkId)
                {
                    case 1:
                        addFacebookPage(model);
                        break;

                    case 2:
                        addTwitterFollow(model);
                        break;
                    case 3:
                        addYoutubeSubscriber(model);
                        break;
                    default:
                        throw new Exception("Please enter valid values");
                }
            }
            catch (BadLinkException e)
            {
                ModelState.AddModelError("", e.Message);
                error = true;
            }
            catch (LinkAlreadyExistException e)
            {
                ModelState.AddModelError("", e.Message);
                error = true;
            }
            catch (Exception)
            {
                ModelState.AddModelError("", "Please add a valid page");
                error = true;
            }

            if (error)
            {
                model.SocialNetworks = listaSocialNetworks;
                return View("Add", model);
            }


            _context.SaveChanges();
            return RedirectToAction("index", "home");
        }

        [NonAction]
        private void addFacebookPage(SocialPageFormViewModel model)
        {
            var url = Regex.Match(model.Url, @"http(s)?:\/\/(www\.)?facebook\.com\/[^\/\s]+").ToString();

            if (String.IsNullOrWhiteSpace(url))
            {
                throw new BadLinkException("Please enter a valid facebook page");
            }
            FacebookGraph fbGraph = new FacebookGraph(url);

            FacebookPage fbPage = new FacebookPage()
            {
                Name = model.Name,
                Url = url,
                Cpc = model.Cpc
            };


            var facebookId = fbGraph.takeFacebookId();
            var fbAlreadyAdded = _context.Facebooks.SingleOrDefault(fb => fb.FacebookCode == facebookId);
            var currentUserId = User.Identity.GetUserId();

            if (fbAlreadyAdded == null)
            {
                fbPage.FacebookCode = facebookId;
                fbPage.UserId = currentUserId;

                _context.Facebooks.Add(fbPage);
            }
            else
            {
                if (fbAlreadyAdded.UserId == currentUserId)
                {
                    fbAlreadyAdded.Deleted = false;
                }
                else
                {
                    throw new LinkAlreadyExistException("Link is already added on this social network");
                }
            }

        }


        [NonAction]
        private void addTwitterFollow(SocialPageFormViewModel model)
        {
            var username = Regex.Match(model.Url, @"(?<=\.com\/)[^\/\s]+").ToString();
            if (String.IsNullOrWhiteSpace(username))
            {
                throw new BadLinkException("Please enter a valid twitter url");
            }

            var user = _twitterContext.User.Where(u => u.Type == UserType.Show && u.ScreenName == username).SingleOrDefault();
            if (user == null || user.Protected)
            {
                throw new BadLinkException("This user doesn't exist or it's private");
            }

            var currentUserId = User.Identity.GetUserId();

            var twitter = _context.Twitters.SingleOrDefault(twt => twt.TwitterUsername == username);
            if (twitter != null)
            {
                if (twitter.UserId.Equals(currentUserId))
                {
                    twitter.Deleted = false;
                }
                else
                {
                    throw new LinkAlreadyExistException("This twitter accounts is already added on this site");
                }
            }
            else
            {
                TwitterPage twitterPage = new TwitterPage()
                {
                    Url = "http://twitter.com/" + username,
                    TwitterUsername = username,
                    Name = model.Name,
                    Cpc = model.Cpc,
                    UserId = currentUserId
                };

                _context.Twitters.Add(twitterPage);
            }
        }

        [NonAction]
        private void addYoutubeSubscriber(SocialPageFormViewModel model)
        {
            var url = Regex.Match(model.Url, @"http(s):\/\/(www\.)youtube\.com\/(user|channel)\/[^\/\s]+").ToString();
            string usernameOrId = Regex.Match(url, @"(?<=channel\/|user\/)[^\/\s]+").ToString();

            if (String.IsNullOrWhiteSpace(url) || String.IsNullOrWhiteSpace(usernameOrId))
            {
                throw new BadLinkException("This youtube link isn't good. Try to add something like this https://youtube.com/channel/youtube");
            }

            YoutubePage newYoutubePage = new YoutubePage()
            {
                Cpc = model.Cpc,
                Name = model.Name,
                Url = url
            };


            var youtubeService = new YouTubeService(new BaseClientService.Initializer()
            {
                ApiKey = "AIzaSyDp5rhMI0dW7uHIYhq0_iLS9vW5pgy1oy0",
            });

            var request = youtubeService.Channels.List("statistics");

            if (model.Url.Contains("channel"))
            {
                request.Id = usernameOrId;
            }
            else
            {
                request.ForUsername = usernameOrId;
            }

            var response = request.Execute();

            var userRetrieveFromYt = response.Items.SingleOrDefault();

            if (userRetrieveFromYt == null)
            {
                throw new BadLinkException("This user doesn't exist");
            }
            else
            {
                if (userRetrieveFromYt.Statistics.HiddenSubscriberCount == true)
                {
                    throw new BadLinkException("You must not hide the subscribers counter");
                }

                var currentUserId = User.Identity.GetUserId();
                newYoutubePage.UserId = currentUserId;
                newYoutubePage.YoutubeUsername = userRetrieveFromYt.Id;
                var ytAlreadyAdded = _context.Youtubes.SingleOrDefault(y => y.YoutubeUsername == newYoutubePage.YoutubeUsername);


                if (ytAlreadyAdded == null)
                {
                    _context.Youtubes.Add(newYoutubePage);
                }
                else
                {
                    if (ytAlreadyAdded.UserId.Equals(currentUserId))
                    {
                        ytAlreadyAdded.Deleted = false;

                    }
                    else
                    {
                        throw new LinkAlreadyExistException("This channel is already added on this site");
                    }
                }

            }
        }

        public ActionResult Add()
        {
            var listaSocialNetworks = _context.SocialNetworks.ToList();
            var model = new SocialPageFormViewModel()
            {
                SocialNetworks = listaSocialNetworks,
                Cpc = 10
            };
            return View("Add", model);
        }

        [Route("SocialPage/Edit/{type:regex(facebook|twitter|youtube)}/{id}")]
        public ActionResult Edit(string type, int id)
        {
            var currentUserId = User.Identity.GetUserId();
            SocialPage page = null;
            var SocialPageEdit = new EditViewModel();


            if (type.Equals("facebook"))
            {
                page = _context.Facebooks.SingleOrDefault(fb => fb.Id == id);
                SocialPageEdit.SocialNetworkId = SocialNetwork.FacebookPageLikes;
            }
            else if (type.Equals("twitter"))
            {
                page = _context.Twitters.SingleOrDefault(twt => twt.Id == id);
                SocialPageEdit.SocialNetworkId = SocialNetwork.TwitterFollowers;
            }
            else if (type.Equals("youtube"))
            {
                page = _context.Youtubes.SingleOrDefault(yt => yt.Id == id);
                SocialPageEdit.SocialNetworkId = SocialNetwork.YoutubeSubscribers;
            }
            else
            {
                return HttpNotFound();
            }
            if (page == null)

Social Media Exchanger/Views/SocialPage/Add.cshtml
@model Social_Media_Exchanger.ViewModels.SocialPageFormViewModel

@{
    ViewBag.Title = "Add";
}

<h2>Add Page</h2>


@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <hr />
        @Html.ValidationSummary(true)

        <div class="form-group">
            @Html.LabelFor(model => model.SocialNetworkId, new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownListFor(model => model.SocialNetworkId, new SelectList(Model.SocialNetworks, "SocialNetworkId","Name"), new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.SocialNetworkId)
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Name, new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.TextBoxFor(model => model.Name, new { type = "text", @class = "form-control" })
                @Html.ValidationMessageFor(model => model.Name)
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Url, new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.TextBoxFor(model => model.Url, new {type="text", @class="form-control"})
                @Html.ValidationMessageFor(model => model.Url)
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Cpc, new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.TextBoxFor(model => model.Cpc, new { type="number", min="2", max="10"})
                @Html.ValidationMessageFor(model => model.Cpc)
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

Social Media Exchanger/Views/SocialPage/Edit.cshtml
@model Social_Media_Exchanger.ViewModels.EditViewModel

@{
    ViewBag.Title = "Edit";
}

<h2>Edit</h2>

@using (Html.BeginForm("Save","SocialPage")) { 
    <div class="form-horizontal">
        <hr />
        @Html.ValidationSummary(true)
        @Html.HiddenFor(model => model.Id)
        @Html.HiddenFor(model => model.SocialNetworkId)

        <div class="form-group">
            @Html.LabelFor(model => model.Name, new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.TextBoxFor(model => model.Name, new { type = "text", @class = "form-control" })
                @Html.ValidationMessageFor(model => model.Name)
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Cpc, new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.TextBoxFor(model => model.Cpc, new { type = "number", min = "2", max = "10" })
                @Html.ValidationMessageFor(model => model.Cpc)
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Active, new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.CheckBoxFor(model => model.Active)
                @Html.ValidationMessageFor(model => model.Active)
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Edit" class="btn btn-default" />
            </div>
        </div>
    </div>
}

Social Media Exchanger/Views/SocialPage/Index.cshtml
@model Social_Media_Exchanger.ViewModels.MySocialPagesViewModel
@{
    ViewBag.Title = "My Sites";
}

<h2>My sites</h2>
<center><div id="txtHint" style="display:none"></div></center>
@if (Model.numberOfPages > 0)
{
    <div class="container">
        <div class="row">
            <div class="col-xs-12">
                <table class="table table-bordered table-hover table-responsive" style="text-align:center">
                    <thead>
                        <tr>
                            <th class="col-md-2 th-center">Type</th>
                            <th class="col-md-4 th-center">Title</th>
                            <th class="col-md-1 th-center">Clicks</th>
                            <th class="col-md-1 th-center">Cpc</th>
                            <th class="col-md-2 th-center">Edit</th>
                            <th class="col-md-2 th-center">Remove</th>
                        </tr>
                    </thead>
                    <tbody>
                        @foreach (var item in Model.FacebookPages)
                {
                            <tr>
                                <td>
                                    Facebook like
                                </td>
                                <td>
                                    <a href="@item.Url" style="text-decoration:none">@item.Name</a>
                                </td>
                                <td>
                                    @Html.DisplayFor(model => item.NumberOfClicks)
                                </td>
                                <td>
                                    @Html.DisplayFor(model => item.Cpc)
                                </td>
                                <td>
                                    @Html.ActionLink("Edit", "Edit", new { type = "facebook", id = item.Id })
                                </td>
                                <td>
                                    <a class="js-delete" href="#" data-record-id="@item.Id" data-type="facebook">
                                        Delete
                                    </a>
                                </td>
                            </tr>
                }

                        @foreach (var item in Model.TwitterPages)
                {
                            <tr>
                                <td>
                                    Twitter Follow
                                </td>
                                <td>
                                    <a href="@item.Url" style="text-decoration:none">@item.Name</a>
                                </td>
                                <td>
                                    @Html.DisplayFor(model => item.NumberOfClicks)
                                </td>
                                <td>
                                    @Html.DisplayFor(model => item.Cpc)
                                </td>
                                <td>
                                    @Html.ActionLink("Edit", "Edit", new { type = "twitter", id = item.Id })
                                </td>
                                <td>
                                    <a class="js-delete" href="#" data-record-id="@item.Id" data-type="twitter">
                                        Delete
                                    </a>
                                </td>
                            </tr>
                }

                        @foreach (var item in Model.YoutubePages)
                {
                            <tr>
                                <td>
                                    Youtube Subscribe
                                </td>
                                <td>
                                    <a href="@item.Url" style="text-decoration:none">@item.Name</a>
                                </td>
                                <td>
                                    @Html.DisplayFor(model => item.NumberOfClicks)
                                </td>
                                <td>
                                    @Html.DisplayFor(model => item.Cpc)
                                </td>
                                <td>
                                    @Html.ActionLink("Edit", "Edit", new { type = "youtube", id = item.Id })
                                </td>
                                <td>
                                    <a class="js-delete" href="#" data-record-id="@item.Id" data-type="youtube">
                                        Delete
                                    </a>
                                </td>
                            </tr>
                }
                    </tbody>
                </table>
            </div>
        </div>
    </div>
}
else
{
    <div class="container">
        <div class="jumbotron">
            <h1>You doesn't have any page.</h1>
            <p>Add a page and begin to receive the power of the social media</p>
        </div>
    </div>
}
    @section scripts
{
    <script>
        $('.js-delete').on('click', function (e) {
            var $modalDiv = $(e.delegateTarget);
            var idData = $(this).data('recordId');
            var type = $(this).data('type');

            bootbox.confirm("Are you sure you want to delete this page?",function (result) {
                if (result)
                {
                    $.post('/' + type + '/delete', { id: idData })
                        .done(function (html) {
                            $modalDiv.closest('tr').remove();
                            $("#txtHint").replaceWith(html);
                        });
                }
            });

        });        
    </script>
}